#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
STYLE="mytheme"
RASI="$DIR/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
    -kb-cancel Alt-F1 \
    -theme ${RASI}
